# Generated by Django 5.2.7 on 2025-10-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='minimum_workers',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('experience_years', models.IntegerField()),
                ('start_date_experience_years', models.DateField()),
                ('hourly_rate', models.IntegerField()),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='main.coffeeshop')),
            ],
        ),
    ]
