# Generated by Django 5.2.7 on 2025-10-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coffeeshop_minimum_workers_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='main.coffeeshop'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('another_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_shift', to='main.coffeeshop')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coffeeshop')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
        ),
    ]
