# Generated by Django 5.2.7 on 2025-11-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_worker_fired_at_alter_worker_coffee_shop_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
