# Generated by Django 5.2.7 on 2026-01-19 17:06

from django.db import migrations, models
from django.utils.text import slugify

def transliterate(text):
    translit_map = {
        'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo',
        'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm',
        'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
        'ф': 'f', 'х': 'h', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'sch',
        'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya',
        'А': 'A', 'Б': 'B', 'В': 'V', 'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'Yo',
        'Ж': 'Zh', 'З': 'Z', 'И': 'I', 'Й': 'Y', 'К': 'K', 'Л': 'L', 'М': 'M',
        'Н': 'N', 'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'У': 'U',
        'Ф': 'F', 'Х': 'H', 'Ц': 'Ts', 'Ч': 'Ch', 'Ш': 'Sh', 'Щ': 'Sch',
        'Ъ': '', 'Ы': 'Y', 'Ь': '', 'Э': 'E', 'Ю': 'Yu', 'Я': 'Ya'
    }
    result = ''
    for char in text:
        result += translit_map.get(char, char)
    return result

def populate_slugs(apps, schema_editor):
    CoffeeShop = apps.get_model('main', 'CoffeeShop')
    for shop in CoffeeShop.objects.all():
        if not shop.slug:
            transliterated = transliterate(shop.name)
            base_slug = slugify(transliterated)
            slug = base_slug
            counter = 1
            existing_slugs = set()
            for s in CoffeeShop.objects.exclude(id=shop.id):
                if s.slug:
                    existing_slugs.add(s.slug)
            while slug in existing_slugs:
                slug = f"{base_slug}-{counter}"
                counter += 1
            shop.slug = slug
            shop.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shift_is_plus_alter_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=50),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='coffeeshop',
            name='slug',
            field=models.SlugField(blank=True, unique=True, max_length=50),
        ),
    ]
