# Generated by Django 6.0.1 on 2026-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_coffeeshop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
