# Generated by Django 6.0.1 on 2026-01-26 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_worker_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500, verbose_name='Причина отдачи смены')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('APPROVED', 'Подтверждено'), ('REJECTED', 'Отклонено'), ('TAKEN', 'Взято другим работником'), ('CANCELED', 'Отменено')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shift_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop_admins',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Супер-админ'), ('SHOP_ADMIN', 'Админ точки'), ('WORKER', 'Работник')], default='WORKER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='replacement_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_shifts', to='main.worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='main.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='main.worker'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('worker', 'date')},
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['coffee_shop', 'date'], name='shifts_coffee__80c188_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['worker', 'date'], name='shifts_worker__a0c9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date'], name='shifts_date_338aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['coffee_shop', 'fired_at'], name='workers_coffee__705f47_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['user'], name='workers_user_id_ec2ee4_idx'),
        ),
        migrations.AlterModelTable(
            name='shift',
            table='shifts',
        ),
        migrations.AlterModelTable(
            name='worker',
            table='workers',
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.shift'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_shifts', to='main.worker'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='main.worker'),
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='main.coffeeshop'),
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shiftrequest',
            index=models.Index(fields=['status', 'requested_at'], name='shift_reque_status_142662_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftrequest',
            index=models.Index(fields=['shift', 'status'], name='shift_reque_shift_i_e8e950_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftrequest',
            index=models.Index(fields=['worker', 'status'], name='shift_reque_worker__9e12ec_idx'),
        ),
        migrations.AddIndex(
            model_name='shopadmin',
            index=models.Index(fields=['user', 'coffee_shop'], name='shop_admins_user_id_d7777c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopadmin',
            unique_together={('user', 'coffee_shop')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'),
        ),
    ]
