# Generated by Django 6.0.1 on 2026-02-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shiftrequest_shopadmin_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='vacation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
