# Generated by Django 6.0.1 on 2026-02-08 11:19

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_worker_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
