# Generated by Django 6.0.1 on 2026-02-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_worker_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='main.shift'),
        ),
    ]
