# Generated by Django 6.0.1 on 2026-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_shiftrequest_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='hourly_rate',
            field=models.IntegerField(default=2400),
        ),
    ]
