# Generated by Django 6.0.1 on 2026-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_worker_hourly_rate_coffeeshop_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('APPROVED', 'Подтверждено'), ('REJECTED', 'Отклонено'), ('TAKEN', 'Взято другим работником'), ('CANCELED', 'Отменено'), ('AWAITING_TAKER', 'Ждет подтверждения работника')], default='PENDING', max_length=20),
        ),
    ]
