# Generated by Django 6.0.1 on 2026-02-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_shiftrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='experience_years',
            field=models.FloatField(default=0),
        ),
    ]
