# Generated by Django 6.0.1 on 2026-02-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_worker_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='coffee_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='main.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='start_date_experience_years',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
