# Generated by Django 6.0.1 on 2026-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_worker_coffee_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='display_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
