# Generated by Django 6.0.1 on 2026-03-09 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_pushsubscriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('TECH_CHART', 'Техкарта'), ('PRICE_LIST', 'Прайс-лист'), ('OTHER', 'Прочее')], default='OTHER', max_length=20, verbose_name='Категория')),
                ('item_type', models.CharField(choices=[('FILE', 'Файл (PDF/Изображение)'), ('TEXT', 'Текст/Таблица')], default='FILE', max_length=10, verbose_name='Тип контента')),
                ('file', models.FileField(blank=True, null=True, upload_to='help/', verbose_name='Файл')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текст/Контент')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Справочный материал',
                'verbose_name_plural': 'Справочные материалы',
                'db_table': 'help_items',
                'ordering': ['category', '-uploaded_at'],
            },
        ),
    ]
